version: '3.8'

services: 
  ulectures-api: 
    container_name: ulecture-backend
    # image: node:10.23.3
    build: ./
    command: npm start
    working_dir: /usr/src/ulectures-api
    ports:
      - "5000:5000"